# spring.application.name=edu2

# # DB 설정
# spring.datasource.url = jdbc:mysql://localhost:3306/ict_db
# spring.datasource.username = ictedu
# spring.datasource.password = 1111
# spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# # 생략 가능
# server.port = 8080

# mybatis.mapper-locations=mapper/*.xml
# mybatis.type-aliases-package=com.ict.edu2
# # mybatis.type-aliases-package=com.ict.edu2.domain


spring:
  application:
    name : edu3

  datasource:
    url : jdbc:mysql://localhost:3306/ict_db
    username : ictedu
    password : 1111
    driver-class-name : com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: file:D:/upload/
      # static-locations: classpath:/static/

  security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: 2f249e8e63c23abbda96d05efa33f0e7
              client-secret: AYg6TEkTvZ4MnG0fziWs3hkzkfJisDDj
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              authorization-grant-type: authorization_code
              client-authentication-method: client_secret_post
              client-name: Kakao
              scope:
                - profile_nickname
                - profile_image
                - account_email
            naver:
              client-id: VklLQp2NB9yJ6m59cB1w
              client-secret:  8QEeYnPD7V
              redirect-uri: http://localhost:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              client-name: Naver
              scope:
                - name
                - email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response


# 파일 업로드 기능에서 파일이 저장될 물리적 경로를 명시
file:
  upload-dir: D:/upload

server:
  port : 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations : mapper/*.xml
  type-aliases-package : com.ict.edu3
# mybatis.type-aliases-package=com.ict.edu2.domain

# 비밀키 사용(32바이트 길이)
jwt:
  secret : "qPwOeIrUtYqPwOeIrUtYqPwOeIrUtY10"
  expiration : 3600000 # 1시간

